[package]
name = "hero_studio"
version = "0.1.0"
authors = ["Christian Perez-Llamas"]

[dependencies]
docopt = "0.7.0"
rand = "0.3.15"

portaudio = "0.7.0"
portmidi = "^0.2"
rosc = "0.1.5"
tokio-core = "0.1.4"
futures = "0.1.10"

hero_core = { path = "../core" }
hero_synth = { path = "../synth" }
